{{- if or .Values.serviceAccount.create .Values.tailscale.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uptime-kuma.serviceAccountName" . }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
