{{- if .Values.global.mariadb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptime-kuma-bundle.fullname" . }}-db
  labels:
    {{- include "uptime-kuma-bundle.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.global.mariadb.service.type }}
  ports:
    - port: {{ .Values.global.mariadb.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "uptime-kuma-bundle.mariadb.selectorLabels" . | nindent 4 }}
{{- end }}
