{{- if .Values.global.tailscale.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tailscale-auth
stringData:
  TS_AUTHKEY: {{ .Values.global.tailscale.auth | quote }}
{{- end -}}
